/**
 * Mock RAP servers — spins up 3 HTTP servers on ports 4001, 4002, 4003.
 * Reads private keys from .keys.demo.json (generated by seed-demo.ts).
 * Signs all AgentCards with the org private key at startup.
 *
 * Endpoints (per §2.1):
 *   GET /agents.json      → full catalog (§2.4)
 *   GET /agents/:slug     → single AgentCard (§2.3)
 *
 * Run: npm run demo:rap   (after npm run demo:seed)
 */

import { createServer } from 'node:http';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPrivateKey, sign } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const KEYS_FILE = join(__dirname, '..', '.keys.demo.json');

// ── Canonical JSON (§2.5 — identical algorithm to signing.ts) ──────────────

function canonicalize(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return JSON.stringify(value);
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) {
    return '[' + (value as unknown[]).map(canonicalize).join(',') + ']';
  }
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    return (
      '{' +
      keys.map((k) => `${JSON.stringify(k)}:${canonicalize(obj[k])}`).join(',') +
      '}'
    );
  }
  throw new Error(`canonicalize: unsupported type ${typeof value}`);
}

/**
 * Signs an AgentCard with the org private key (§2.5).
 * Strips the `signature` field before canonicalizing — matching the
 * verifyAgentCardSignature logic in services/signing.ts.
 */
function signAgentCard(
  card: Record<string, unknown>,
  privateKeyPem: string,
): string {
  const { signature: _strip, ...payload } = card;
  const data = Buffer.from(canonicalize(payload), 'utf8');
  const key = createPrivateKey(privateKeyPem);
  return sign(null, data, key).toString('base64');
}

// ── Types ───────────────────────────────────────────────────────────────────

interface KeyPair {
  privateKey: string;
  publicKey: string;
}

type KeyStore = Record<string, KeyPair>;

interface AgentCardDef {
  slug: string;
  display_name: string;
  description: string;
  capabilities: string[];
  protocol: 'a2a' | 'mcp' | 'rest';
}

interface OrgConfig {
  ownerId: string;
  port: number;
  agents: AgentCardDef[];
}

// ── Org + agent definitions ─────────────────────────────────────────────────

const ORGS: OrgConfig[] = [
  {
    ownerId: 'acme',
    port: 4001,
    agents: [
      {
        slug: 'billing-agent',
        display_name: 'Acme Billing Agent',
        description: 'Handles billing inquiries, invoice retrieval, and payment status.',
        capabilities: ['billing.invoice', 'billing.payment', 'billing.dispute'],
        protocol: 'a2a',
      },
      {
        slug: 'support-agent',
        display_name: 'Acme Support Agent',
        description: 'Customer support ticket management and live chat routing.',
        capabilities: ['support.ticket', 'support.chat', 'support.escalate'],
        protocol: 'rest',
      },
    ],
  },
  {
    ownerId: 'globex',
    port: 4002,
    agents: [
      {
        slug: 'inventory-agent',
        display_name: 'Globex Inventory Agent',
        description: 'Real-time inventory query and stock update operations.',
        capabilities: ['inventory.query', 'inventory.update', 'inventory.reserve'],
        protocol: 'a2a',
      },
      {
        slug: 'pricing-agent',
        display_name: 'Globex Pricing Agent',
        description: 'Dynamic pricing lookup and bulk pricing negotiation.',
        capabilities: ['pricing.lookup', 'pricing.bulk', 'pricing.negotiate'],
        protocol: 'mcp',
      },
    ],
  },
  {
    ownerId: 'initech',
    port: 4003,
    agents: [
      {
        slug: 'hr-agent',
        display_name: 'Initech HR Agent',
        description: 'Employee onboarding workflows and HR policy queries.',
        capabilities: ['hr.onboarding', 'hr.policy', 'hr.leave'],
        protocol: 'a2a',
      },
      {
        slug: 'it-helpdesk-agent',
        display_name: 'Initech IT Helpdesk Agent',
        description: 'IT ticket creation, password resets, and equipment requests.',
        capabilities: ['it.ticket', 'it.reset', 'it.equipment'],
        protocol: 'rest',
      },
    ],
  },
];

// ── Build and sign agent cards at startup ───────────────────────────────────

interface SignedAgentCard extends Record<string, unknown> {
  id: string;
  display_name: string;
  description: string;
  version: string;
  capabilities: string[];
  invocation_url: string;
  protocol: string;
  visibility: 'public';
  signed_by: string;
  created_at: string;
  updated_at: string;
  signature: string;
}

interface OrgCatalog {
  owner_id: string;
  domain: string;
  generated_at: string;
  catalog_version: number;
  agents: SignedAgentCard[];
}

function buildOrgCatalog(
  org: OrgConfig,
  keyPair: KeyPair,
  keyId: string,
): Map<string, SignedAgentCard> {
  const port = org.port;
  const baseUrl = `http://localhost:${port}`;
  const now = new Date().toISOString();

  const cards = new Map<string, SignedAgentCard>();

  for (const def of org.agents) {
    const unsigned: Record<string, unknown> = {
      id: `${org.ownerId}/${def.slug}`,
      display_name: def.display_name,
      description: def.description,
      version: '1.0.0',
      capabilities: def.capabilities,
      invocation_url: `${baseUrl}/invoke/${def.slug}`,
      protocol: def.protocol,
      visibility: 'public' as const,
      signed_by: keyId,
      created_at: now,
      updated_at: now,
    };

    const signature = signAgentCard(unsigned, keyPair.privateKey);
    const signed: SignedAgentCard = { ...unsigned, signature } as SignedAgentCard;
    cards.set(def.slug, signed);
  }

  return cards;
}

// ── HTTP server factory ─────────────────────────────────────────────────────

function startServer(
  org: OrgConfig,
  cards: Map<string, SignedAgentCard>,
): void {
  const catalog: OrgCatalog = {
    owner_id: org.ownerId,
    domain: `${org.ownerId}.demo`,
    generated_at: new Date().toISOString(),
    catalog_version: 1,
    agents: Array.from(cards.values()),
  };

  const catalogJson = JSON.stringify(catalog);

  const server = createServer((req: IncomingMessage, res: ServerResponse) => {
    const url = req.url ?? '/';

    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', 'max-age=86400');

    if (url === '/agents.json') {
      res.writeHead(200);
      res.end(catalogJson);
      return;
    }

    if (url.startsWith('/agents/')) {
      const slug = url.slice('/agents/'.length);
      const card = cards.get(slug);

      if (!card) {
        res.writeHead(404);
        res.end(JSON.stringify({ error: 'AGENT_NOT_FOUND', slug }));
        return;
      }

      res.writeHead(200);
      res.end(JSON.stringify(card));
      return;
    }

    res.writeHead(404);
    res.end(JSON.stringify({ error: 'NOT_FOUND' }));
  });

  server.listen(org.port, () => {
    console.log(
      `  [${org.ownerId}] RAP running on http://localhost:${org.port} ` +
      `(${cards.size} agents: ${Array.from(cards.keys()).join(', ')})`,
    );
  });
}

// ── Main ────────────────────────────────────────────────────────────────────

function main(): void {
  let keyStore: KeyStore;
  try {
    keyStore = JSON.parse(readFileSync(KEYS_FILE, 'utf8')) as KeyStore;
  } catch {
    console.error(
      `Error: .keys.demo.json not found. Run "npm run demo:seed" first.`,
    );
    process.exit(1);
  }

  const KEY_IDS: Record<string, string> = {
    acme: 'acme-agent-root-demo',
    globex: 'globex-agent-root-demo',
    initech: 'initech-agent-root-demo',
  };

  console.log('Mock RAP servers starting…');

  for (const org of ORGS) {
    const keyPair = keyStore[org.ownerId];
    if (!keyPair) {
      console.error(`Error: no key pair found for ${org.ownerId} in .keys.demo.json`);
      process.exit(1);
    }
    const keyId = KEY_IDS[org.ownerId] ?? `${org.ownerId}-agent-root-demo`;
    const cards = buildOrgCatalog(org, keyPair, keyId);
    startServer(org, cards);
  }

  console.log('\nAll mock RAPs running. Press Ctrl+C to stop.');
}

main();
