/**
 * Mock RAP servers — spins up HTTP servers for each org on its assigned port.
 * Reads private keys from .keys.demo.json (generated by seed-demo.ts).
 * Signs all AgentCards with the org private key at startup.
 *
 * Endpoints (per §2.1):
 *   GET  /agents.json     → full catalog (§2.4)
 *   GET  /agents/:slug    → single AgentCard (§2.3)
 *   POST /agents          → register a new agent (L2 demo). Body:
 *                           { name, display_name, description, capabilities[],
 *                             protocol, invocation_url }
 *                           RAP signs with the org root key, stores in-memory,
 *                           returns the signed AgentCard with 201.
 *
 * CORS: wide-open Access-Control-Allow-Origin:* so the garr-web frontend
 * can register agents directly from the browser.
 *
 * Run: npm run demo:rap   (after npm run demo:seed)
 */

import { createServer } from 'node:http';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPrivateKey, sign } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const KEYS_FILE = join(__dirname, '..', '.keys.demo.json');

// ── Canonical JSON (§2.5 — identical algorithm to signing.ts) ──────────────

function canonicalize(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return JSON.stringify(value);
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) {
    return '[' + (value as unknown[]).map(canonicalize).join(',') + ']';
  }
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    return (
      '{' +
      keys.map((k) => `${JSON.stringify(k)}:${canonicalize(obj[k])}`).join(',') +
      '}'
    );
  }
  throw new Error(`canonicalize: unsupported type ${typeof value}`);
}

function signAgentCard(
  card: Record<string, unknown>,
  privateKeyPem: string,
): string {
  const { signature: _strip, ...payload } = card;
  const data = Buffer.from(canonicalize(payload), 'utf8');
  const key = createPrivateKey(privateKeyPem);
  return sign(null, data, key).toString('base64');
}

// ── Types ───────────────────────────────────────────────────────────────────

interface KeyPair {
  privateKey: string;
  publicKey: string;
}

type KeyStore = Record<string, KeyPair>;

interface AgentCardDef {
  slug: string;
  display_name: string;
  description: string;
  capabilities: string[];
  protocol: 'a2a' | 'mcp' | 'rest';
  invocation_url?: string;
}

interface OrgConfig {
  ownerId: string;
  port: number;
  agents: AgentCardDef[];
}

// ── Org + agent definitions (manager's example: search@google ↔ products@meta) ─

const ORGS: OrgConfig[] = [
  {
    ownerId: 'google',
    port: 4001,
    agents: [
      {
        slug: 'search-agent',
        display_name: 'Google Search Agent',
        description: 'Performs web search queries and returns ranked results.',
        capabilities: ['search.web', 'search.image', 'search.news'],
        protocol: 'a2a',
        invocation_url: 'https://google.demo/a2a/search',
      },
    ],
  },
  {
    ownerId: 'meta',
    port: 4002,
    agents: [
      {
        slug: 'products-agent',
        display_name: 'Meta Products Agent',
        description: 'Catalog and product-information lookup across Meta marketplaces.',
        capabilities: ['products.lookup', 'products.recommend', 'products.inventory'],
        protocol: 'a2a',
        invocation_url: 'https://meta.demo/a2a/products',
      },
    ],
  },
];

// ── Signed card shape ───────────────────────────────────────────────────────

interface SignedAgentCard extends Record<string, unknown> {
  id: string;
  display_name: string;
  description: string;
  version: string;
  capabilities: string[];
  invocation_url: string;
  protocol: string;
  visibility: 'public';
  signed_by: string;
  created_at: string;
  updated_at: string;
  signature: string;
}

// ── Build and sign agent cards at startup ───────────────────────────────────

function buildAndSignCard(
  ownerId: string,
  port: number,
  keyPair: KeyPair,
  keyId: string,
  def: AgentCardDef,
): SignedAgentCard {
  const baseUrl = `http://localhost:${port}`;
  const now = new Date().toISOString();

  const unsigned: Record<string, unknown> = {
    id: `${ownerId}/${def.slug}`,
    display_name: def.display_name,
    description: def.description,
    version: '1.0.0',
    capabilities: def.capabilities,
    invocation_url: def.invocation_url ?? `${baseUrl}/invoke/${def.slug}`,
    protocol: def.protocol,
    visibility: 'public' as const,
    signed_by: keyId,
    created_at: now,
    updated_at: now,
  };

  const signature = signAgentCard(unsigned, keyPair.privateKey);
  return { ...unsigned, signature } as SignedAgentCard;
}

function buildOrgCatalog(
  org: OrgConfig,
  keyPair: KeyPair,
  keyId: string,
): Map<string, SignedAgentCard> {
  const cards = new Map<string, SignedAgentCard>();
  for (const def of org.agents) {
    cards.set(def.slug, buildAndSignCard(org.ownerId, org.port, keyPair, keyId, def));
  }
  return cards;
}

// ── HTTP helpers ────────────────────────────────────────────────────────────

const NAME_RE = /^[a-z0-9-]+$/;

function setCors(res: ServerResponse): void {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

function readJsonBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk: Buffer) => chunks.push(chunk));
    req.on('end', () => {
      try {
        const text = Buffer.concat(chunks).toString('utf8');
        resolve(text.length === 0 ? {} : JSON.parse(text));
      } catch (err) {
        reject(err);
      }
    });
    req.on('error', reject);
  });
}

interface RegisterAgentBody {
  name?: unknown;
  display_name?: unknown;
  description?: unknown;
  capabilities?: unknown;
  protocol?: unknown;
  invocation_url?: unknown;
}

function validateAgentBody(body: RegisterAgentBody): AgentCardDef | string {
  const name = body.name;
  if (typeof name !== 'string' || !NAME_RE.test(name)) {
    return 'name must match ^[a-z0-9-]+$';
  }
  const display_name = body.display_name;
  if (typeof display_name !== 'string' || display_name.length === 0) {
    return 'display_name is required';
  }
  const description = typeof body.description === 'string' ? body.description : '';
  const capabilitiesRaw = body.capabilities;
  if (!Array.isArray(capabilitiesRaw) || !capabilitiesRaw.every((c) => typeof c === 'string')) {
    return 'capabilities must be a string[]';
  }
  const protocol = body.protocol;
  if (protocol !== 'a2a' && protocol !== 'rest' && protocol !== 'mcp') {
    return "protocol must be one of 'a2a' | 'rest' | 'mcp'";
  }
  const invocation_url = typeof body.invocation_url === 'string' && body.invocation_url.length > 0
    ? body.invocation_url
    : undefined;
  return {
    slug: name,
    display_name,
    description,
    capabilities: capabilitiesRaw as string[],
    protocol,
    invocation_url,
  };
}

// ── HTTP server factory ─────────────────────────────────────────────────────

function startServer(
  org: OrgConfig,
  cards: Map<string, SignedAgentCard>,
  keyPair: KeyPair,
  keyId: string,
): void {
  const buildCatalogJson = (): string =>
    JSON.stringify({
      owner_id: org.ownerId,
      domain: `${org.ownerId}.demo`,
      generated_at: new Date().toISOString(),
      catalog_version: 1,
      agents: Array.from(cards.values()),
    });

  const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
    setCors(res);
    res.setHeader('Content-Type', 'application/json');

    const method = req.method ?? 'GET';
    const url = req.url ?? '/';

    if (method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    if (method === 'GET' && url === '/agents.json') {
      res.setHeader('Cache-Control', 'no-store');
      res.writeHead(200);
      res.end(buildCatalogJson());
      return;
    }

    if (method === 'GET' && url.startsWith('/agents/')) {
      const slug = url.slice('/agents/'.length);
      const card = cards.get(slug);
      if (!card) {
        res.writeHead(404);
        res.end(JSON.stringify({ error: 'AGENT_NOT_FOUND', slug }));
        return;
      }
      res.setHeader('Cache-Control', 'no-store');
      res.writeHead(200);
      res.end(JSON.stringify(card));
      return;
    }

    if (method === 'POST' && url === '/agents') {
      let body: RegisterAgentBody;
      try {
        body = (await readJsonBody(req)) as RegisterAgentBody;
      } catch {
        res.writeHead(400);
        res.end(JSON.stringify({ error: 'INVALID_JSON' }));
        return;
      }

      const result = validateAgentBody(body);
      if (typeof result === 'string') {
        res.writeHead(422);
        res.end(JSON.stringify({ error: 'VALIDATION_FAILED', detail: result }));
        return;
      }

      if (cards.has(result.slug)) {
        res.writeHead(409);
        res.end(JSON.stringify({ error: 'AGENT_EXISTS', slug: result.slug }));
        return;
      }

      const signed = buildAndSignCard(org.ownerId, org.port, keyPair, keyId, result);
      cards.set(result.slug, signed);
      console.log(`  [${org.ownerId}] + registered new agent ${result.slug}`);
      res.writeHead(201);
      res.end(JSON.stringify(signed));
      return;
    }

    res.writeHead(404);
    res.end(JSON.stringify({ error: 'NOT_FOUND' }));
  });

  server.listen(org.port, () => {
    console.log(
      `  [${org.ownerId}] RAP running on http://localhost:${org.port} ` +
      `(${cards.size} agents: ${Array.from(cards.keys()).join(', ')})`,
    );
  });
}

// ── Main ────────────────────────────────────────────────────────────────────

const KEY_IDS: Record<string, string> = {
  google: 'google-agent-root-demo',
  meta: 'meta-agent-root-demo',
};

function main(): void {
  let keyStore: KeyStore;
  try {
    keyStore = JSON.parse(readFileSync(KEYS_FILE, 'utf8')) as KeyStore;
  } catch {
    console.error(
      `Error: .keys.demo.json not found. Run "npm run demo:seed" first.`,
    );
    process.exit(1);
  }

  console.log('Mock RAP servers starting…');

  for (const org of ORGS) {
    const keyPair = keyStore[org.ownerId];
    if (!keyPair) {
      console.error(`Error: no key pair found for ${org.ownerId} in .keys.demo.json`);
      process.exit(1);
    }
    const keyId = KEY_IDS[org.ownerId] ?? `${org.ownerId}-agent-root-demo`;
    const cards = buildOrgCatalog(org, keyPair, keyId);
    startServer(org, cards, keyPair, keyId);
  }

  console.log('\nAll mock RAPs running. Press Ctrl+C to stop.');
}

main();
